### ISSUE TITLE
Use modern router that’s has the needed cross platform features all working 

### ISSUE THREAD

**Issue by gedw99** [ahammer/dart_board#1]
The way the code works now is really great the large projects but it’s missing the modern router features.

https://github.com/tomgilder/routemaster Has been and continues to prove valuable .
Wen and native Orks
Uses the standard context
Deep links, share, notifications just works . Relies on unilinks 

There are many other navigator 2.0 routers out there also but I liked routemaater because it’s a nice balance between taking over but giving you room to move 

The imperative route builder i think fits the needs of dart board also but let you decide

**Comment by ahammer** [comment]
I'll dissect routemaster for ideas.

However unlikely to migrate to nav 2.0 at this time (for a 1.0 release). I may provide a Nav 2.0 sample in a feature module (I think it's possible because embedded navigators are allowed, but I need to explore the idea more).

Additionally I really want to limit my 3rd party deps at least in the core. I took provider to kill boilerplate for me, but will maybe remove it in the future from the core. Ideally, core will become a no-deps library.

**Comment by ahammer** [comment]
Going to close for now, however feel free to open another issue if it can be linked to a specific desired feature/bug. E.g. URL deep linking support.

It will help me better prioritize how to attack nav 2.0 in the future and how to prioritize features. Some features like better URL support probably can be added via the core, as the RouteDefinition interface is pretty flexible, I only provided one implementation (NamedRouteDefinition) to begin with, but I suspect it has some room to grow before hitting it's limits (e.g. I could make a UrlRouteDefinition, or others).

**Comment by ahammer** [comment]
edit, I should add one thing though, on the imperative front, there is the same options as Navigator 1.

So you can still push a material page route with any builder. If you want Page Decorations you can use the ApplyPageDecorations method in core (usually at least paired with a route name, to support allow/deny filtering, but that can be any unique name).

But I did build in hooks to handle most peoples custom routing needs via the named routing. E.g. changing the Route that is used globally or on a per named route basis, but you can take full control and push any route.

You can also use RouteWidget() to use named routes as a child widget to a screen. So you can fake out nav patterns very easily. E.g. the entire example only loads the /main route, all bottom-nav/code tabs are fake nav, using RouteWidget as a container inside a TabView or AnimatedSwitcher. All nav state is stored in widget state in the example. So it's similar to a Nav 2.0 bespoke solution, just without using navigator 2.0.

**Comment by gedw99** [comment]
Thanks for the explanation and I can see you have many of the modern router aspects already.

will kick the tires and raise issues on anything I come across
