### ISSUE TITLE
Remote config ?

### ISSUE THREAD

**Issue by gedw99** [ahammer/dart_board#2]
Does it make sense to use this with remote config like the Firebase one ?

Seems like a good match

**Comment by ahammer** [comment]
I am amicable to firebase auth and firebase remote config as features.

If someone could make a feature, they could set up a remote config->feature mapping to manage the system by including the firebase auth and passing a config through.

The only thing not really demonstrated in the repo required to achieve this is key management/config.

I know I want config to come down through the main() (e.g. firebase api keys), But I'm not sure how I want to handle keys and the repo and example yet.


To build the feature, it would look something like this.
- create new module, dart_board_firebase_remote_config
- add a feature class
- Create a AppDecoration that provides a widget that handles the firebase connection and retrieving/updating remote config
- Interface with DartBoard the same way in /debug route to switch features

The Feature probably should take a function that maps firebase config -> feature config (with maybe a default that imposes a naming on both sides) and the API Key for firebase.

I'm happy to take contributions if you, or anyone wants to attempt this.

**Comment by ahammer** [comment]
It'll probably be a bit down the road for me though, at least priority wise.

Will keep this issue open for any discussion or volunteers.

**Comment by ahammer** [comment]
I'll likely add remote config and firebase analytics soon. I've added Auth and Firestore in a branch, will merge and release and likely put out a Remote Config feature next.

**Comment by ahammer** [comment]
FlutterFire remote config doesn't support web yet, so I'm not going to implement it right now.

Remote Config could be faked with FireStore across all features. I'll probably look back to this in the future.
